import type { Casa } from '@/types/presets'

export type BonoListadoEspana = Pick<Casa, 'id' | 'nombre' | 'market' | 'pais' | 'url'> & {
  ofertaTexto: string
}

export type BonoListadoCasa = BonoListadoEspana | Casa

export type BonoMercadoLatamUs = 'REG' | 'CL' | 'PE' | 'EC' | 'MX' | 'CO' | 'AR' | 'PA' | 'UY' | 'US'
export type BonoConfianzaLatamUs = 'alta' | 'media' | 'baja'
export type BonoDecisionLatamUs = 'ok' | 'prudente' | 'revisar'

export type BonoLatamUsCurado = {
  nombre: string
  mercado: BonoMercadoLatamUs
  red: string
  ofertaTexto: string
  usdAprox: number
  confianza: BonoConfianzaLatamUs
  decision: BonoDecisionLatamUs
  url: string
}

export const bonosEspanaCurados: BonoListadoEspana[] = [
  {
    id: '888sport',
    nombre: '888Sport',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/888Sport/136728/1',
    ofertaTexto: '10€ gratis al registrarte + 1ª apuesta asegurada hasta 100€',
  },
  {
    id: 'bet777',
    nombre: 'Bet777',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Bet777/145118/1',
    ofertaTexto: 'Freebet de 10€ con tu primer depósito',
  },
  {
    id: 'betfair',
    nombre: 'Betfair',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Betfair/139419/2',
    ofertaTexto: 'Bono del 400% hasta 200€ · apuesta hasta 50€ y recibe hasta 200€ de bono',
  },
  {
    id: 'betsson',
    nombre: 'Betsson',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Betsson/136727/1',
    ofertaTexto: '100% extra hasta 100€ con tu primer depósito',
  },
  {
    id: 'betway',
    nombre: 'Betway',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/popup18/21553?url=https%3A%2F%2Fapp.afiliago.com%2Fgo%2F21553%2FfIkqcOFwoh%2F2',
    ofertaTexto: 'Hasta 200€ Free Bet + 50 Free Spins si pierdes tu primera apuesta',
  },
  {
    id: 'casino-gran-madrid',
    nombre: 'Casino Gran Madrid',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/21694/3kE5KVXDC1/2',
    ofertaTexto: 'Hasta 200€ con tu primer depósito',
  },
  {
    id: 'codere',
    nombre: 'Codere',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Codere/136722/1',
    ofertaTexto: '100% de tu primer depósito hasta 200€',
  },
  {
    id: 'golden-bull',
    nombre: 'Golden Bull',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/goldenbull/145119/1',
    ofertaTexto: 'FreeBet 10€',
  },
  {
    id: 'goldenpark',
    nombre: 'GoldenPark',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/popup18/19149?url=https%3A%2F%2Fapp.afiliago.com%2Fgo%2F19149%2FWs1nYCo4gw',
    ofertaTexto: 'Bono hasta 100€ gratis',
  },
  {
    id: 'interwetten',
    nombre: 'Interwetten',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Interwetten/136723/1',
    ofertaTexto: '50€ Freebet para nuevos usuarios',
  },
  {
    id: 'kirolbet',
    nombre: 'Kirolbet',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Kirolbet/101909/1',
    ofertaTexto: '100€ Freebets + 50 tiradas gratis · código KB100',
  },
  {
    id: 'lsbet',
    nombre: 'LSbet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/7vutqmwx',
    ofertaTexto: 'Bono de bienvenida hasta 120€',
  },
  {
    id: 'luckia',
    nombre: 'Luckia',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Luckia/145120/1',
    ofertaTexto: 'Bono de bienvenida hasta 200€',
  },
  {
    id: 'marca-apuestas',
    nombre: 'Marca Apuestas',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/marcaapuestas/136724/1',
    ofertaTexto: 'Gana hasta 200€ gratis',
  },
  {
    id: 'optimbet',
    nombre: 'OptimBet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/nex0qo1g',
    ofertaTexto: 'Paquete de bienvenida hasta 300€',
  },
  {
    id: 'paf',
    nombre: 'PAF',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/PAF/100477/1',
    ofertaTexto: 'Hasta 20€ en Freebets',
  },
  {
    id: 'pokerstars',
    nombre: 'PokerStars',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/PokerStars/101907/1',
    ofertaTexto: 'Hasta 100€ en apuestas gratuitas si tu primera apuesta resulta perdedora',
  },
  {
    id: 'slottojam',
    nombre: 'SlottoJAM',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/9duezfia',
    ofertaTexto: 'Paquete de bienvenida hasta 300€',
  },
  {
    id: 'sportium',
    nombre: 'Sportium',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Sportium/136726/1',
    ofertaTexto: 'Doble bono hasta 200€',
  },
  {
    id: 'tornadobet',
    nombre: 'TornadoBet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/ke1cz7hv',
    ofertaTexto: 'Paquete de bienvenida hasta 300€',
  },
  {
    id: 'versus',
    nombre: 'Versus',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/19148/JqXVcHDWdu/2',
    ofertaTexto: 'Hasta 200€ con tus dos primeros depósitos',
  },
  {
    id: 'william-hill',
    nombre: 'William Hill',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/WilliamHill/136725/1',
    ofertaTexto: 'Hasta 200€ asegurados en tu primera apuesta',
  },
  {
    id: 'winamax',
    nombre: 'Winamax',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Winamax/99945/1',
    ofertaTexto: '150€ de Freebets',
  },
  {
    id: 'yosports',
    nombre: 'YoSports',
    market: 'espana',
    pais: 'espana',
    url: 'https://www.yosports.es/promociones/apuesta-gratis-bienvenida?btag=a_10275b_25c_',
    ofertaTexto: 'Hasta 150€ en bonos de bienvenida',
  },
]

export const bonosLatamUsCurados: BonoLatamUsCurado[] = [
  {
    nombre: 'LSbet',
    mercado: 'REG',
    red: 'Stake Partners',
    ofertaTexto: '100% hasta ~US$142 en el primer depósito',
    usdAprox: 142,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://go.aff.o-affiliates.com/6zopm8zq',
  },
  {
    nombre: 'ReloadBet',
    mercado: 'REG',
    red: 'Stake Partners',
    ofertaTexto: '100% hasta ~US$142 de bono de bienvenida deportes',
    usdAprox: 142,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://go.aff.o-affiliates.com/njgymawo',
  },
  {
    nombre: 'Betfair LATAM',
    mercado: 'REG',
    red: 'Bdeal',
    ofertaTexto: 'Apuesta US$10 y recibe US$10 en freebet',
    usdAprox: 10,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/betfair/101912/1',
  },
  {
    nombre: '20Bet LATAM',
    mercado: 'REG',
    red: 'Bdeal',
    ofertaTexto: '100% primer depósito · tope variable por país (~US$100 en CL)',
    usdAprox: 100,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://bdeal.io/20Bet/145125/1',
  },
  {
    nombre: '22Bet LATAM',
    mercado: 'REG',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$148 en apuestas deportivas',
    usdAprox: 148,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/22Bet/101911/1',
  },
  {
    nombre: 'BetWinner LATAM',
    mercado: 'REG',
    red: 'Bdeal',
    ofertaTexto: '100% hasta US$120 con el primer depósito',
    usdAprox: 120,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/Betwinner/145130/1',
  },
  {
    nombre: 'DafaBet LATAM',
    mercado: 'REG',
    red: 'Afiliago',
    ofertaTexto: '100% hasta ~US$177 de bienvenida',
    usdAprox: 177,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://app.afiliago.com/go/19151/EVvuzd0cDG/2',
  },
  {
    nombre: 'Betano CL',
    mercado: 'CL',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$223 al primer depósito',
    usdAprox: 223,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://bdeal.io/Betano/144460/1',
  },
  {
    nombre: 'Betsson CL',
    mercado: 'CL',
    red: 'Bdeal',
    ofertaTexto: 'Hasta ~US$446 + 200 giros gratis',
    usdAprox: 446,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/Betsson/144464/1',
  },
  {
    nombre: 'Betway CL',
    mercado: 'CL',
    red: 'Bdeal',
    ofertaTexto: '100% primer depósito hasta ~US$167',
    usdAprox: 167,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/betway/144468/1',
  },
  {
    nombre: 'Novibet CL',
    mercado: 'CL',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$223 al primer depósito',
    usdAprox: 223,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/novibet/144470/1',
  },
  {
    nombre: 'BetSala CL',
    mercado: 'CL',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$279 al primer depósito',
    usdAprox: 279,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://bdeal.io/Betsala/145128/1',
  },
  {
    nombre: 'Coolbet CL',
    mercado: 'CL',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$223 al primer depósito',
    usdAprox: 223,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://bdeal.io/coolbet/145137/1',
  },
  {
    nombre: 'LVBET CL',
    mercado: 'CL',
    red: 'LVBET Partners',
    ofertaTexto: '100% hasta ~US$112 al primer depósito',
    usdAprox: 112,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://ads.lvbetpartners.com/redirect.aspx?pid=26861&bid=4359',
  },
  {
    nombre: 'Betano PE',
    mercado: 'PE',
    red: 'Bdeal',
    ofertaTexto: 'Freebet de ~US$24 con primer depósito',
    usdAprox: 24,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/Betano/144462/1',
  },
  {
    nombre: 'Betsson PE',
    mercado: 'PE',
    red: 'Bdeal',
    ofertaTexto: 'Freebet de ~US$30 + 30 giros gratis',
    usdAprox: 30,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/Betsson/144464/1',
  },
  {
    nombre: 'Betcris PE',
    mercado: 'PE',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$103 al primer depósito',
    usdAprox: 103,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/Betcris/145126/1',
  },
  {
    nombre: 'Betsafe PE',
    mercado: 'PE',
    red: 'Bdeal',
    ofertaTexto: 'Freebet de ~US$19 + 20 giros gratis',
    usdAprox: 19,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/betsafe/145127/1',
  },
  {
    nombre: 'Coolbet PE',
    mercado: 'PE',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$59 con primer depósito',
    usdAprox: 59,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://bdeal.io/coolbet/145136/1',
  },
  {
    nombre: 'Inkabet PE',
    mercado: 'PE',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$148 al primer depósito',
    usdAprox: 148,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/inkabet/145135/1',
  },
  {
    nombre: 'LVBET PE',
    mercado: 'PE',
    red: 'LVBET Partners',
    ofertaTexto: '100% hasta US$30 al primer depósito',
    usdAprox: 30,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://ads.lvbetpartners.com/redirect.aspx?pid=26861&bid=4365',
  },
  {
    nombre: 'Betano EC',
    mercado: 'EC',
    red: 'Bdeal',
    ofertaTexto: '100% hasta US$300 al primer depósito',
    usdAprox: 300,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/Betano/144461/1',
  },
  {
    nombre: 'Novibet EC',
    mercado: 'EC',
    red: 'Bdeal',
    ofertaTexto: '100% hasta US$100 al primer depósito',
    usdAprox: 100,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/novibet/144474/1',
  },
  {
    nombre: 'Betway EC',
    mercado: 'EC',
    red: 'Bdeal',
    ofertaTexto: '100% hasta US$150 al primer depósito',
    usdAprox: 150,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/betway/144468/1',
  },
  {
    nombre: 'Betano MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$173 al primer depósito',
    usdAprox: 173,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://bdeal.io/betano/144459/1',
  },
  {
    nombre: 'Codere MX',
    mercado: 'MX',
    red: 'Afiliago',
    ofertaTexto: '200% hasta ~US$289 al depósito para apuestas',
    usdAprox: 289,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://app.afiliago.com/go/21809/rYJ2UQPNE3',
  },
  {
    nombre: 'Novibet MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$289 + ~US$12 en apuesta gratis + 50 giros',
    usdAprox: 300,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/novibet/144473/1',
  },
  {
    nombre: 'Sportiumbet MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: 'Apuesta sin riesgo hasta ~US$289',
    usdAprox: 289,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/sportium/144465/1',
  },
  {
    nombre: 'Caliente MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: 'Bono sin depósito de ~US$58',
    usdAprox: 58,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/caliente/145131/1',
  },
  {
    nombre: 'Calupoh MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: 'Apuesta ~US$14 y gana ~US$12',
    usdAprox: 12,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/Calupoh/145140/1',
  },
  {
    nombre: 'Jugabet MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$289 al primer depósito',
    usdAprox: 289,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/Jugabet/145133/1',
  },
  {
    nombre: 'Versusbet MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$578 en apuestas deportivas',
    usdAprox: 578,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/versusbet/145146/1',
  },
  {
    nombre: 'Winner MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$289 al primer depósito',
    usdAprox: 289,
    confianza: 'alta',
    decision: 'ok',
    url: 'https://bdeal.io/winner/145145/1',
  },
  {
    nombre: 'Winpot MX',
    mercado: 'MX',
    red: 'Bdeal',
    ofertaTexto: '~US$29 en freebet + 100% hasta ~US$173',
    usdAprox: 202,
    confianza: 'media',
    decision: 'prudente',
    url: 'https://bdeal.io/Winpot/145144/1',
  },
  {
    nombre: 'Wplay CO',
    mercado: 'CO',
    red: 'Bdeal',
    ofertaTexto: 'Bono sin depósito de ~US$30',
    usdAprox: 30,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/wplay/144472/1',
  },
  {
    nombre: 'Sportium CO',
    mercado: 'CO',
    red: 'Bdeal',
    ofertaTexto: 'Dobla hasta ~US$14',
    usdAprox: 14,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/Sportium/144466/1',
  },
  {
    nombre: 'Betsson CO',
    mercado: 'CO',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$55 al primer depósito',
    usdAprox: 55,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/betsson/144463/1',
  },
  {
    nombre: 'Luckia CO',
    mercado: 'CO',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$69 en la primera recarga',
    usdAprox: 69,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/Luckia/144471/1',
  },
  {
    nombre: 'Betano AR',
    mercado: 'AR',
    red: 'Bdeal',
    ofertaTexto: '100% hasta ~US$368 + ~US$15 en apuesta gratis',
    usdAprox: 383,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/betano/144459/1',
  },
  {
    nombre: 'Codere AR',
    mercado: 'AR',
    red: 'Afiliago',
    ofertaTexto: 'Duplica tu primer depósito hasta ~US$147',
    usdAprox: 147,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://app.afiliago.com/go/21810/oOjTG1953F',
  },
  {
    nombre: 'Betway PA',
    mercado: 'PA',
    red: 'Bdeal',
    ofertaTexto: '100% primer depósito hasta US$75',
    usdAprox: 75,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/betway/144468/1',
  },
  {
    nombre: 'Sportium PA',
    mercado: 'PA',
    red: 'Bdeal',
    ofertaTexto: 'US$5 gratis + 100% hasta US$150 en freebet',
    usdAprox: 155,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/Sportium/144467/1',
  },
  {
    nombre: 'Betway UY',
    mercado: 'UY',
    red: 'Bdeal',
    ofertaTexto: '100% primer depósito hasta US$75',
    usdAprox: 75,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/betway/144468/1',
  },
  {
    nombre: 'BetUS',
    mercado: 'US',
    red: 'Bdeal',
    ofertaTexto: '125% hasta US$3,125 en el primer depósito',
    usdAprox: 3125,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/BetUS/145129/1',
  },
  {
    nombre: 'MyBookie',
    mercado: 'US',
    red: 'Bdeal',
    ofertaTexto: '100% hasta US$1,000 en el primer depósito',
    usdAprox: 1000,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/mybookie/145155/1',
  },
  {
    nombre: 'Thunderpick US',
    mercado: 'US',
    red: 'Bdeal',
    ofertaTexto: '100% hasta US$600',
    usdAprox: 600,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/thunderpick/145148/1',
  },
  {
    nombre: 'Xbet',
    mercado: 'US',
    red: 'Bdeal',
    ofertaTexto: '50% hasta US$200 en el primer depósito',
    usdAprox: 200,
    confianza: 'baja',
    decision: 'revisar',
    url: 'https://bdeal.io/Xbet/145143/1',
  },
]
