import type { Casa } from '@/types/presets'

export type BonoListadoEspana = Pick<Casa, 'id' | 'nombre' | 'market' | 'pais' | 'url'> & {
  ofertaTexto: string
}

export type BonoListadoCasa = BonoListadoEspana | Casa

export const bonosEspanaCurados: BonoListadoEspana[] = [
  {
    id: '888sport',
    nombre: '888Sport',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/888Sport/136728/1',
    ofertaTexto: '10€ gratis al registrarte + 1ª apuesta asegurada hasta 100€',
  },
  {
    id: 'bet777',
    nombre: 'Bet777',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Bet777/145118/1',
    ofertaTexto: 'Freebet de 10€ con tu primer depósito',
  },
  {
    id: 'betfair',
    nombre: 'Betfair',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Betfair/139419/2',
    ofertaTexto: 'Bono del 400% hasta 200€ · apuesta hasta 50€ y recibe hasta 200€ de bono',
  },
  {
    id: 'betsson',
    nombre: 'Betsson',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Betsson/136727/1',
    ofertaTexto: '100% extra hasta 100€ con tu primer depósito',
  },
  {
    id: 'betway',
    nombre: 'Betway',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/popup18/21553?url=https%3A%2F%2Fapp.afiliago.com%2Fgo%2F21553%2FfIkqcOFwoh%2F2',
    ofertaTexto: 'Hasta 200€ Free Bet + 50 Free Spins si pierdes tu primera apuesta',
  },
  {
    id: 'casino-gran-madrid',
    nombre: 'Casino Gran Madrid',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/21694/3kE5KVXDC1/2',
    ofertaTexto: 'Hasta 200€ con tu primer depósito',
  },
  {
    id: 'codere',
    nombre: 'Codere',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Codere/136722/1',
    ofertaTexto: '100% de tu primer depósito hasta 200€',
  },
  {
    id: 'golden-bull',
    nombre: 'Golden Bull',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/goldenbull/145119/1',
    ofertaTexto: 'FreeBet 10€',
  },
  {
    id: 'goldenpark',
    nombre: 'GoldenPark',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/popup18/19149?url=https%3A%2F%2Fapp.afiliago.com%2Fgo%2F19149%2FWs1nYCo4gw',
    ofertaTexto: 'Bono hasta 100€ gratis',
  },
  {
    id: 'interwetten',
    nombre: 'Interwetten',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Interwetten/136723/1',
    ofertaTexto: '50€ Freebet para nuevos usuarios',
  },
  {
    id: 'kirolbet',
    nombre: 'Kirolbet',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Kirolbet/101909/1',
    ofertaTexto: '100€ Freebets + 50 tiradas gratis · código KB100',
  },
  {
    id: 'lsbet',
    nombre: 'LSbet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/7vutqmwx',
    ofertaTexto: 'Bono de bienvenida hasta 120€',
  },
  {
    id: 'luckia',
    nombre: 'Luckia',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Luckia/145120/1',
    ofertaTexto: 'Bono de bienvenida hasta 200€',
  },
  {
    id: 'marca-apuestas',
    nombre: 'Marca Apuestas',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/marcaapuestas/136724/1',
    ofertaTexto: 'Gana hasta 200€ gratis',
  },
  {
    id: 'optimbet',
    nombre: 'OptimBet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/nex0qo1g',
    ofertaTexto: 'Paquete de bienvenida hasta 300€',
  },
  {
    id: 'paf',
    nombre: 'PAF',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/PAF/100477/1',
    ofertaTexto: 'Hasta 20€ en Freebets',
  },
  {
    id: 'pokerstars',
    nombre: 'PokerStars',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/PokerStars/101907/1',
    ofertaTexto: 'Hasta 100€ en apuestas gratuitas si tu primera apuesta resulta perdedora',
  },
  {
    id: 'slottojam',
    nombre: 'SlottoJAM',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/9duezfia',
    ofertaTexto: 'Paquete de bienvenida hasta 300€',
  },
  {
    id: 'sportium',
    nombre: 'Sportium',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Sportium/136726/1',
    ofertaTexto: 'Doble bono hasta 200€',
  },
  {
    id: 'tornadobet',
    nombre: 'TornadoBet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/ke1cz7hv',
    ofertaTexto: 'Paquete de bienvenida hasta 300€',
  },
  {
    id: 'versus',
    nombre: 'Versus',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/19148/JqXVcHDWdu/2',
    ofertaTexto: 'Hasta 200€ con tus dos primeros depósitos',
  },
  {
    id: 'william-hill',
    nombre: 'William Hill',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/WilliamHill/136725/1',
    ofertaTexto: 'Hasta 200€ asegurados en tu primera apuesta',
  },
  {
    id: 'winamax',
    nombre: 'Winamax',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Winamax/99945/1',
    ofertaTexto: '150€ de Freebets',
  },
  {
    id: 'yosports',
    nombre: 'YoSports',
    market: 'espana',
    pais: 'espana',
    url: 'https://www.yosports.es/promociones/apuesta-gratis-bienvenida?btag=a_10275b_25c_',
    ofertaTexto: 'Hasta 150€ en bonos de bienvenida',
  },
]
