import type { Casa } from '@/types/presets'

export type BonoListadoCasa = Pick<Casa, 'id' | 'nombre' | 'market' | 'pais' | 'url' | 'beneficioPotencial'>

export const bonosEspanaCurados: BonoListadoCasa[] = [
  {
    id: '888sport',
    nombre: '888Sport',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/888Sport/136728/1',
    beneficioPotencial: 75,
  },
  {
    id: 'bet777',
    nombre: 'Bet777',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Bet777/145118/1',
    beneficioPotencial: 10,
  },
  {
    id: 'betfair',
    nombre: 'Betfair',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Betfair/139419/2',
    beneficioPotencial: 150,
  },
  {
    id: 'betsson',
    nombre: 'Betsson',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Betsson/136727/1',
    beneficioPotencial: 50,
  },
  {
    id: 'betway',
    nombre: 'Betway',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/popup18/21553?url=https%3A%2F%2Fapp.afiliago.com%2Fgo%2F21553%2FfIkqcOFwoh%2F2',
    beneficioPotencial: 140,
  },
  {
    id: 'casino-gran-madrid',
    nombre: 'Casino Gran Madrid',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/21694/3kE5KVXDC1/2',
    beneficioPotencial: 62,
  },
  {
    id: 'codere',
    nombre: 'Codere',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Codere/136722/1',
    beneficioPotencial: 65,
  },
  {
    id: 'golden-bull',
    nombre: 'Golden Bull',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/goldenbull/145119/1',
    beneficioPotencial: 10,
  },
  {
    id: 'goldenpark',
    nombre: 'GoldenPark',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/popup18/19149?url=https%3A%2F%2Fapp.afiliago.com%2Fgo%2F19149%2FWs1nYCo4gw',
    beneficioPotencial: 50,
  },
  {
    id: 'interwetten',
    nombre: 'Interwetten',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Interwetten/136723/1',
    beneficioPotencial: 35,
  },
  {
    id: 'kirolbet',
    nombre: 'Kirolbet',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Kirolbet/101909/1',
    beneficioPotencial: 100,
  },
  {
    id: 'lsbet',
    nombre: 'LSbet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/7vutqmwx',
    beneficioPotencial: 120,
  },
  {
    id: 'luckia',
    nombre: 'Luckia',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Luckia/145120/1',
    beneficioPotencial: 200,
  },
  {
    id: 'marca-apuestas',
    nombre: 'Marca Apuestas',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/marcaapuestas/136724/1',
    beneficioPotencial: 90,
  },
  {
    id: 'optimbet',
    nombre: 'OptimBet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/nex0qo1g',
    beneficioPotencial: 300,
  },
  {
    id: 'paf',
    nombre: 'PAF',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/PAF/100477/1',
    beneficioPotencial: 14,
  },
  {
    id: 'pokerstars',
    nombre: 'PokerStars',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/PokerStars/101907/1',
    beneficioPotencial: 60,
  },
  {
    id: 'slottojam',
    nombre: 'SlottoJAM',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/9duezfia',
    beneficioPotencial: 300,
  },
  {
    id: 'sportium',
    nombre: 'Sportium',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Sportium/136726/1',
    beneficioPotencial: 140,
  },
  {
    id: 'tornadobet',
    nombre: 'TornadoBet',
    market: 'espana',
    pais: 'espana',
    url: 'https://go.aff.o-affiliates.com/ke1cz7hv',
    beneficioPotencial: 300,
  },
  {
    id: 'versus',
    nombre: 'Versus',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/19148/JqXVcHDWdu/2',
    beneficioPotencial: 65,
  },
  {
    id: 'william-hill',
    nombre: 'William Hill',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/WilliamHill/136725/1',
    beneficioPotencial: 130,
  },
  {
    id: 'winamax',
    nombre: 'Winamax',
    market: 'espana',
    pais: 'espana',
    url: 'https://bdeal.io/Winamax/99945/1',
    beneficioPotencial: 70,
  },
  {
    id: 'yosports',
    nombre: 'YoSports',
    market: 'espana',
    pais: 'espana',
    url: 'https://app.afiliago.com/go/21535/At5p84GuWP/2',
    beneficioPotencial: 50,
  },
]
